### ISSUE TITLE
Count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by bognarjunior** [LiliomLab/laravel-firebase#4]
Hello, @Hussam3bd.
I have a erro:
"Count(): Parameter must be an array or an object that implements Countable" in FirebaseMessage.php line 293.

However in the commit 7bae8c3989ba6bc0228152fe081420d8876af033, this erro has already been fixed.

But I use the composer update or I delete the "vendor" and reinstall the package again and the code does not modify, is there something missing?

Obs: The package code does not change too.

**Comment by Hussam3bd** [comment]
Hi @bognarjunior,
Thank you for informing us, we didn't release the new commit that @Evertt mead
However try now `composer update` and I hope everything gonna be okay
